### ISSUE TITLE
Crystal Armour Set not Accounted for

### ISSUE THREAD

**Issue by Vagrant3124** [LlemonDuck/dps-calculator#102]
Just what the title says. With the bowfa the set effect (15% damage and 30% accuracy bonus) isn't being applied. Attached is proof, using the dps calc made by Bitter.
![Screenshot_48](https://github.com/LlemonDuck/dps-calculator/assets/134745586/a3e3f4d6-ad88-4405-9d30-7af9c3c7771e)
![Screenshot_49](https://github.com/LlemonDuck/dps-calculator/assets/134745586/dc8deb53-2606-47dd-b0f7-8d3d5853756a)

**Comment by brickinthewall4138** [comment]
Are you using the recoloured crystal armour? There's a fix for that already, but it's not in the live plugin yet. 

If not, are you on task? Maybe the slayer helm bonuses aren't detected correctly.

**Comment by Vagrant3124** [comment]
Yeah it must be because of the recolour.
My bad I didn't even think of that, good to know there is already a fix!
