### ISSUE TITLE
Runelite client unable to open

### ISSUE THREAD

**Issue by MosheBenZacharia** [LlemonDuck/dps-calculator#109]
Hello,

there seems to be an issue with DPS calc preventing runelite from opening.

Here is the thread dump:

[dpscalc.log](https://github.com/LlemonDuck/dps-calculator/files/12518941/dpscalc.log)

**Comment by Felanbird** [comment]
As a note this seems to be related to some [fire Github has going on](https://www.githubstatus.com/incidents/c8zjb9351hlc), I noticed the rl website was loading very slowly, as well as the logs supplied by other users showed `Resource Packs` timing out, but only DPS Calc seems to be hindering the client from starting.

**Comment by brickinthewall4138** [comment]
>  only DPS Calc seems to be hindering the client from starting.

can you clarify how you confirmed that, as unfortunately it seems to already be fixed so I can't see for myself.

**Comment by MosheBenZacharia** [comment]
> can you clarify how you confirmed that

I launched the client in debug mode from IntelliJ and it would fully hang during "starting plugins". I took a a thread dump from IntelliJ and saw that callstack in the AWT thread. 

Disabling the plugin resolved the issue for everyone who was also experiencing the hang.

**Comment by LlemonDuck** [comment]
I've pushed a new commit that defers plugin loading until the github data can be pulled, and does so asynchronously. Might be vulnerable to race conditions toggling plugin on/off while loading, but for most cases it should be quick enough that it doesn't matter.

1b4e92c57e4fec84bbfb9701ece81c11e408c9cc
