### ISSUE TITLE
Attack style could be loaded from client as well. The official plugin does this and shows it in an overlay.

### ISSUE THREAD

**Issue by 3ICE** [LlemonDuck/dps-calculator#11]
https://github.com/runelite/runelite/wiki/Attack-Styles
No need to make us manually set it.

**Comment by LlemonDuck** [comment]
I was aware of this and it was a little more complex than it seems at first. It is on the slate for things to add.

**Comment by LlemonDuck** [comment]
Done in 896c6f3c822e4642b624d92d878453af68ad92f0. Also should select spell, if autocasting.

**Comment by LlemonDuck** [comment]
I've finally added autocast spell detection in 4e2893f45abcce2f2e3186734e285a10d7e77d3b, so I'm staging this for release, and going to publish version 1.3 now.
