### ISSUE TITLE
Can't use both offensive melee prayers at once (Ultimate Strength + Incredible reflexes) because they share the same dropdown unfortunately.

### ISSUE THREAD

**Issue by 3ICE** [LlemonDuck/dps-calculator#12]
Please fix. I pray both attack and str. Either with a change from simple to combo dropdown or just putting even more checkboxes below.

Also I had no idea prior to raising this issue what all the various prayers names are, I had to look it up specifically for this plugin.
Icons would be preferred. And/or better sorting and categorization (range/melee/magic, tier 1/2/3).

**Comment by LlemonDuck** [comment]
Nice, I didn't even know that was possible. I'll see if I can rework it to maybe just look like the normal prayer tab with all icons, so you can click them to toggle. If that doesn't work, I might just expand them all into checkboxes with categories like you mentioned.

**Comment by LlemonDuck** [comment]
Added in 67aea2d2367d54bf2d570587c3fe5b549789df29 and staged for release in 1.3.

New prayer panel will look like this:
![image](https://user-images.githubusercontent.com/1868974/120903546-a8e29800-c614-11eb-9ae3-f9948f74816b.png)

**Comment by LlemonDuck** [comment]
Added in #54, pending release to plugin hub

**Comment by LlemonDuck** [comment]
Linked this incorrectly to #54, this is still resolved
