### ISSUE TITLE
The Gauntlet (&Corrupted) Staves

### ISSUE THREAD

**Issue by TimOosterom** [LlemonDuck/dps-calculator#16]
All the staves in The Gauntlet have a set max hit that's independent level and spell (was tested during Leagues).

Currently, the plugin requires a spell for these powered staves, instead of treating them like a trident.

**Comment by LlemonDuck** [comment]
From what I see on the wiki link below, the max hit table includes annotations that say the max hits are reached at level 99. Do you have a source on how the max hit is calculated for these weapons if it is different from the usual?

I will admit I don't think I added in any spell for the Crystal Staff, so it is likely wrong, but I can't find information on the wiki for how its max hit is calculated, in order to implement it correctly.

https://oldschool.runescape.wiki/w/The_Gauntlet#Weapons

**Comment by TimOosterom** [comment]
Fairly hard to find a direct source/actual proof, but I'll try and hit some JMods up for information. 

A video from Trailblazers is the best I can do for now besides my own experience, it shows a person hitting a 24 at level 42 Magic using the Attuned staff (31 max hit): https://youtu.be/0jCeJiTdu-Q?t=404

I'll update here when I get an actual reply from a JMod.

**Comment by TimOosterom** [comment]
https://twitter.com/JagexAsh/status/1416678805322838018

> Hey Ash, can you confirm the staves in The Gauntlet have a max hit independent of your (current) Magic level? As in, the perfect staff can always hit a 39.

Confirmed. Rather like the basic elemental spells, where the max hit is simply determined by the spell - though outside the gauntlet there are obviously more modifier effects that could be relevant.

**Comment by LlemonDuck** [comment]
Nice source! I'll take it.

I've responded to the thread also asking for the max hit of the tier 1 and tier 2 staves. I'll add them all together as one patch if I get a response. Otherwise, I'll add the tier 3 for now and revisit if needed.

**Comment by TimOosterom** [comment]
The wiki does have the max hits for the staves listed (23 & 31) on their respective pages. No actual source, though, but they seem in line from what I've seen. Would be good to have confirmation from Ash.

https://oldschool.runescape.wiki/w/Crystal_staff_(basic)
https://oldschool.runescape.wiki/w/Crystal_staff_(attuned)

**Comment by LlemonDuck** [comment]
Got a confirmation on those as well, which matches the wiki:

https://twitter.com/JagexAsh/status/1419566600315981824

As well as confirmation that the corrupted variants are the same:

https://twitter.com/JagexAsh/status/1419566647145271304

Added in 42953128. Will likely be a week or two until next release to RuneLite.

**Comment by LlemonDuck** [comment]
This now live, you can update your version by restarting RL or using the Plugin Hub panel to update the plugin.

Thanks for your help on this!
