### ISSUE TITLE
Dragon battleaxe spec boost is calculating higher than it should  

### ISSUE THREAD

**Issue by bugreporter9001** [LlemonDuck/dps-calculator#22]
![image](https://user-images.githubusercontent.com/93479192/139587631-f5773525-27c5-4c0d-9b17-52d08a445130.png)

screenshot below of my stats right after using special - notice strength is only boosted by 15 instead of the suggested 25
![image](https://user-images.githubusercontent.com/93479192/139588246-6dd271bc-fbf1-45a1-af4e-2b2c070289ec.png)

**Comment by LlemonDuck** [comment]
I'm inclined to believe the correct boost is actually 16, not 15, and that you decayed a level as you were taking the screenshot, but I've fixed it now in b412e4dc1b15c7f368b11c793e710f019dac3d42.
