### ISSUE TITLE
Eagle Eye doesn't boost max hit

### ISSUE THREAD

**Issue by ThimbleFire** [LlemonDuck/dps-calculator#27]
![rolfnoplease](https://user-images.githubusercontent.com/14812476/144030778-a14af558-44c3-4299-b20e-ee8342140651.gif)

**Comment by LlemonDuck** [comment]
To be honest I had no idea the lower tier ranged prayers provided a strength bonus, based on their in-game descriptions. Fixed in 6473429397eb4b7c2e9a6ae9b70fca7ac9c4356f
