### ISSUE TITLE
Slayer staff doesn't have all possible spells

### ISSUE THREAD

**Issue by adnapPanda** [LlemonDuck/dps-calculator#29]
The slayer staff is missing some spells, which can be autocast. Notably, all spells from the arceuus spellbook. Possible also spells from other spellbooks.

**Comment by LlemonDuck** [comment]
Humorously, I actually went through and updated the autocast lists recently in ee0f47a26de1b45cd8de43e4d356a1882ee5266b and still got it wrong!

I'll try to update these soon, but it'll be restricted for deployment until at least next Wednesday's game update.

**Comment by LlemonDuck** [comment]
Added in 66407a2, released tonight to plugin hub.
