### ISSUE TITLE
Add an extra option for manual casting

### ISSUE THREAD

**Issue by adnapPanda** [LlemonDuck/dps-calculator#30]
Right now only autocasting is supported. Manual casting would increase the dps slightly and it would allow the selection of spells and magic weapons which can't be autocast (Ex: staff of fire and superior demonbane)

**Comment by LlemonDuck** [comment]
I'm all for adding manual casting, although I'd have to figure out how I want to handle that for equipping non-magic items too. 

> would increase the dps slightly  

Not really, afaik it only casts 1t faster at the start, then still is the same speed, which wouldn't be relevant factor in DPS calculation.

**Comment by adnapPanda** [comment]
> Not really, afaik it only casts 1t faster at the start, then still is the same speed, which wouldn't be a relevant factor in DPS calculation.

Yea, I was wrong about that. My whole life has been a lie.

**Comment by LlemonDuck** [comment]
Added in 392bbe9, released tonight to plugin hub.
