### ISSUE TITLE
Attributes not applying / DPS against revenants incorrect

### ISSUE THREAD

**Issue by YvesW** [LlemonDuck/dps-calculator#32]
Please refer to my comment below for more info about the general problem. This post was written before I found the attributes bug and details how I was alerted to it.

------------
Original post:

A buddy of mine has confirmed that his max hit on revenant demons is 49 with the welfare gear listed below. The DPS calculator only lists a max hit of 41, which very likely also results in incorrect DPS. Below you can find Bitterkoekje's calculator with the exact same gear my friend used as set 1. The max hit of set 1 seems to be correct for Bitterkoekje's, but incorrect for the plugin. The same is probably the case for the DPS.

![dps calc bitterkoekje](https://user-images.githubusercontent.com/7929021/147616094-994e7f7b-bb65-408c-bba0-1b965855eff9.png)
Bracelet of ethereum doesn't have any stats or damage enhancing effects, so no gloves.

![unknown](https://user-images.githubusercontent.com/7929021/147616144-14ad76d9-b975-4bff-b5eb-b3b0f73f1f1c.png)
![image](https://user-images.githubusercontent.com/7929021/147616152-17de14c0-062f-4dbf-a6a3-8c094b2edd78.png)
![image](https://user-images.githubusercontent.com/7929021/147616155-d27e6b0b-b8d7-403f-b95a-1bbd4d2ba3b7.png)
![image](https://user-images.githubusercontent.com/7929021/147616161-284cf78e-7c7a-45ef-9870-88a4dc161581.png)

Calculated DPS with salve (e) was lower according to the plugin IIRC, so I don't expect it to not apply the avarice boost (unless it also doesn't apply the salve boost). However, I haven't really looked into that.

Also tried some different welfare gear (MSB + rune arrows) and it seems like there's also a difference between Bitterkoekje's and the plugin. Please refer to set 2 and ignore set 1, since this is the same as the first one, but with slash instead of crush.
![dps calc bitterkoekje msb](https://user-images.githubusercontent.com/7929021/147616504-96818237-eb0b-48c0-8f9c-01c9152c08a0.png)

![image](https://user-images.githubusercontent.com/7929021/147616519-e1b69c76-4073-4d9a-97d4-1256915d3835.png)
![image](https://user-images.githubusercontent.com/7929021/147616525-65cfd1b1-31d2-4115-8d06-65f7c368448c.png)
![image](https://user-images.githubusercontent.com/7929021/147616533-c17cac5d-bc8b-4d2a-a9fa-8120b95d3367.png)
![image](https://user-images.githubusercontent.com/7929021/147616543-01973796-ab64-49ea-b7aa-18790ff96457.png)
![image](https://user-images.githubusercontent.com/7929021/147616551-ca76056f-72d1-4608-8596-2082a08c9c70.png)

I haven't checked different revenants or gear setups than the one mentioned above.

**Comment by YvesW** [comment]
It looks like there's a bug with applying certain attributes. It seems like some attributes are bugged when using the monster stats from the list and some are even bugged when manually selecting monster stats. 

I used the following gear/stats/prayer as a base for the following testing:
![image](https://user-images.githubusercontent.com/7929021/147617396-bb36d4f5-a5e8-4b1b-a704-440042e854c9.png)
![image](https://user-images.githubusercontent.com/7929021/147617406-7b3c961b-2f45-4427-a407-dec489b2bd91.png)
![image](https://user-images.githubusercontent.com/7929021/147617419-bd2b12db-2cb7-4479-b0d1-f27e8a4d4f32.png)

First case: Vorkath selected from the list of NPCs.
![image](https://user-images.githubusercontent.com/7929021/147617483-b3e91207-7875-4eb1-822a-ff4293ee6bc0.png)
![image](https://user-images.githubusercontent.com/7929021/147617488-fc1dcf22-30a6-4af2-8325-1759e5f06d19.png)

Second case:
Same stats as vorkath, but this time manual entry. Dragon is checked, undead isn't (Vork should be both).
![image](https://user-images.githubusercontent.com/7929021/147617594-175819a7-df37-4086-9520-97cd7224c155.png)
![image](https://user-images.githubusercontent.com/7929021/147617521-5111bb5c-2ffa-4b48-b80e-a283e7505828.png)
DPS increased! So it seems like the dragon aspect was not applied to the monster in the first case. With manual entry, it was applied. 

Third case:
Vork with undead attribute, but not dragon attribute.
![image](https://user-images.githubusercontent.com/7929021/147617623-a82a9d81-0fd5-4bf2-bbe8-1f8127d8bad4.png)
![image](https://user-images.githubusercontent.com/7929021/147617638-6657b262-6a95-4826-af74-14478e9694cb.png)
Same DPS as in the first case, so it looks like the undead attribute was correctly applied in the first case, or... it wasn't applied at all, even after manual entry.

Fourth case:
Vork without any attributes.
![image](https://user-images.githubusercontent.com/7929021/147617702-eb9366a2-493c-49f9-ac61-76c7e11641e2.png)
![image](https://user-images.githubusercontent.com/7929021/147617714-4cddae86-c6cd-4315-8ce7-cd6b6320aee7.png)
The DPS is the same as in the third case! Seems like the salve undead bonus isn't applied when selecting a monster from the list, or when entering monster attributes manually!

So, it very likely didn't apply any undead bonus to the revs.

I haven't checked any other attributes than the ones listed above, but it seems like the attributes + potentially slayer helmet could use a check. I also haven't checked any of these in Bitterkoekje's calc to see if the calculations (e.g. in case 2) are correct.

**Comment by LlemonDuck** [comment]
This was an incredibly lengthy read for a very simple issue. As you can see on the NPC Stats panel, the monster attributes (undead, dragon, etc.) are not being loaded when selecting an NPC that should have these. It appears that the last wiki scrape I performed failed to pull NPC attributes and broke this feature.

I will try to fix this with the Nex gear wiki import tonight.

**Comment by LlemonDuck** [comment]
Fixed in 408567d91d3d2c2ac0a417fea1bf7d5f33a915e8
