### ISSUE TITLE
Super Magic Potion (NMZ) is missing

### ISSUE THREAD

**Issue by stevenwaterman** [LlemonDuck/dps-calculator#33]
https://github.com/LlemonDuck/dps-calculator/blob/41c399e9df78935889a07b792405469117ad7318/src/main/java/com/duckblade/osrs/dpscalc/ui/skills/SkillBoostPreset.java#L23

You have the super ranging potion but not the super magic potion

**Comment by LlemonDuck** [comment]
Fixed in a7ae6b8a00b89638b915c72d83e9408f611bae11
