### ISSUE TITLE
DPS for magic spells is incorrectly using an attack speed of 4 instead of 5

### ISSUE THREAD

**Issue by cow1337killer3** [LlemonDuck/dps-calculator#34]
Combat spells have an attack speed of 5 [3 seconds] (besides powered staves and harmonized nightmare staff which have 4 [2.4 seconds]). 

I'm using a Kodai wand with ice barrage. The DPS calculator is using an attack speed of 4 instead of 5. I think it's looking at the melee attack speed of the wand (which is 4).  It gives me a DPS of 8.542... 8.542 * 2.4 / 3 = 6.8336. This is the number that all other DPS calcs I checked are giving me.

**Comment by cow1337killer3** [comment]
I've been told by someone that this is the most accurate DPS calc: https://docs.google.com/spreadsheets/d/1wBXIlvAmqoQpu5u9XBfD4B0PW7D8owyO_CnRDiTHBKQ/edit#gid=158500257

It's in Excel so I think you should be able to see all the formulas as well.

**Comment by LlemonDuck** [comment]
Fixed in 5985b67012e0b028dab33f2a3409abe60916af78
