### ISSUE TITLE
Wrong dps/max hit with ahrim's + amulet of the damned

### ISSUE THREAD

**Issue by MrMadduckS** [LlemonDuck/dps-calculator#36]
Quote from wiki: "Players wearing an Amulet of the damned and Ahrim's set will be able to autocast Ancient Magicks. In addition, players will hit with **30% increased damage** if the spell is autocast. This effect occurs alongside the normal set effect."
I don't think the 30% increased damage is accounted for at the moment. (The wiki makes it sound like the 30% extra damage only applies when autocasting Ancient Magicks specifically, but it also works for other spellbooks, although its not calculated at all at the moment).

I'm also pretty sure that multiple sources of damage boosts are being calculated wrong at the moment (should be multiplicative).
I hope I can explain.

My setup: Full Ahrim's (5% from the staff), Amulet of the Damned (30% as stated in the quote), Mark of Darkness + Superior Demonbane (25% damage boost while under effect of Mark of Darkness).
I have been shooting black demon's for a while and my max hit was 39. Superior Demonbane's base max is 23.
So: 23 * 1.05 = 24.15 -- 24.15 * 1.30 = 31.395 -- 31.395 * 1.25 = 39.24375
If i calculate it by adding up the damage boosts I get 23 * 1.6 = 36.8 (but i have hit a 39)

The max hit shown by the plugin (taken in account that the 30% damage increased from Ahrim's + damned isn't calculated) is 29.
To get to 29 it adds up the damage boosts and multiplies it by the base max hit (23 * 1.3 = 29.9).
If its calculated multiplicative it is 23 * 1.05 = 24.15 -- 24.15 * 1.25 = 30.1875.

I'm just trying to help, I hope it does! 
Very awesome plugin, thanks alot!

**Comment by LlemonDuck** [comment]
This should be much easier now following b0b7375d6807f5893931a6364009860a92e068ce, but hasn't been implemented yet

**Comment by LlemonDuck** [comment]
Done in f47073e, will add to current hub PR and close when released to public

**Comment by LlemonDuck** [comment]
Added to runelite/plugin-hub#2795
