### ISSUE TITLE
Wrong dps and max hit for blisterwood flail and vyrewatch sentinals

### ISSUE THREAD

**Issue by og841** [LlemonDuck/dps-calculator#37]
All I can say is i'm hitting 50's and it's saying max hit 44

manually entered that i'm on task, manually toggled that and vampyre option, no difference

PS: thanks for the plugin

**Comment by LlemonDuck** [comment]
I don't think I ever added any vampyre-based detection, although the checkbox is present. I'll file this as a bug for now and fix it someday, I guess. If anyone comes across this and would like to fix it, it should be fairly straightforward.

**Comment by pwatts6060** [comment]
Was just about to report this as well, I might make a PR

**Comment by LlemonDuck** [comment]
added in #54, pending release to plugin hub
