### ISSUE TITLE
Weapon mode not selectable for chinchompas

### ISSUE THREAD

**Issue by codekillermuffin** [LlemonDuck/dps-calculator#38]
Tried to equip every color chinchompa. but the "weapon mode" dropdown did not show anything, this means DPS cannot be calculated for chinchompas

**Comment by LlemonDuck** [comment]
This should be much easier now following b0b7375d6807f5893931a6364009860a92e068ce, but hasn't been implemented yet.

Chinchompas will need accuracy calculation based on distance, which requires a new input and UI elements https://oldschool.runescape.wiki/w/Chinchompa#Chinchompa_guide

**Comment by LlemonDuck** [comment]
Reopening until released to plugin hub

**Comment by LlemonDuck** [comment]
Added to runelite/plugin-hub#2795
