### ISSUE TITLE
Setup Comparison

### ISSUE THREAD

**Issue by AnkouOSRS** [LlemonDuck/dps-calculator#4]
First of all, I wanted to say this is an awesome plugin and something I've been looking for for a while. 

One of the biggest things missing in my opinion though is the ability to compare 2 different setups side-by-side. Personally, I think the best way to implement this would be to have another identical "Equipment" page and perhaps rename them to "Setup 1" and "Setup 2", then on the home page where it shows DPS it could show all the same information for both setups. Alternatively, you could keep it all on one equipment page with two separate tabs/sections. This makes it a lot easier to look at how much of a benefit specific changes to the gear will be without having to write the DPS down before messing with the equipment.

**Comment by LlemonDuck** [comment]
Great suggestion, it's one feature I'm also looking forward to having.

**Comment by LlemonDuck** [comment]
Implemented in 91bcb1e29b657a38c5b4013cc30dc2b0649c9eb2. Will be include in release 1.1.
