### ISSUE TITLE
Salve Bonus not Applying

### ISSUE THREAD

**Issue by BLARGoMATIC** [LlemonDuck/dps-calculator#41]
Using the vorkath preset using void range my dps is listed as 6.588 with or with the salve amulet.

I'm using a gif, as still images of the dps screen were identical.
![salve amulet busted](https://user-images.githubusercontent.com/47672542/160150577-c5134165-c232-40f9-9479-a5fd80c5ef20.gif)

equipment: 
![image](https://user-images.githubusercontent.com/47672542/160150986-198c0686-16a2-4f55-b417-155d3075602e.png)

skills: 
![image](https://user-images.githubusercontent.com/47672542/160151073-75a0ee74-44c7-485a-8194-e3aa9ee86a2f.png)

npc stats: 
![image](https://user-images.githubusercontent.com/47672542/160151124-c13c2511-0a1b-463e-8ffe-6ac97c446e6c.png)

prayer: 
![image](https://user-images.githubusercontent.com/47672542/160151168-002294dd-a168-4781-9ce8-92e91c756e3c.png)

**Comment by LlemonDuck** [comment]
Fixed in eef264c8efdec3da82cecad9943ddef1771c9f44.

Closed by runelite/plugin-hub#2494
