### ISSUE TITLE
Group boosts

### ISSUE THREAD

**Issue by vikke1234** [LlemonDuck/dps-calculator#42]
Could the "useful" boosts be added to the top of the preset combo box instead of sorting them [here](https://github.com/LlemonDuck/dps-calculator/blob/eef264c8efdec3da82cecad9943ddef1771c9f44/src/main/java/com/duckblade/osrs/dpscalc/ui/skills/SkillsPanel.java#L76). Would make it a lot easier to quickly choose the ones you need, as it's fairly rare to need to check the dps with a normal attack potion.

**Comment by LlemonDuck** [comment]
Added quick boost buttons for super combat, ranging and imbued heart in 9734e8446728ec9737a277e4cae3b24548a4afcc

![Screenshot_20220429_005956](https://user-images.githubusercontent.com/1868974/165906101-ba3c0f11-b1bb-4ddc-af2d-8c1ec7830b7d.png)
