### ISSUE TITLE
Keris and Keris Partisan do not have bonuses applied to kalphites and scarabites

### ISSUE THREAD

**Issue by Nightfirecat** [LlemonDuck/dps-calculator#44]
Both weapons have the following ability:

> It deals 33% bonus damage against all kalphites and scabarites, and has a 1/51 chance of puncturing a hole in their exoskeleton, dealing triple damage. When the special effect occurs.

**Comment by LlemonDuck** [comment]
Added in a7d5ffba7590463dbef97e3094fad5d7fea183cc

**Comment by icorne** [comment]
Was this ever released? Still get ??? in the toolbox

**Comment by Nightfirecat** [comment]
Yes, it was released in v1.5.2. If your shown dps is ??? you have something unset in one of the input panels, that is not related to this issue.
