### ISSUE TITLE
Dharok set effect

### ISSUE THREAD

**Issue by gerben1234** [LlemonDuck/dps-calculator#46]
there is no way to calculate the dps with the dharoks set effect

**Comment by LlemonDuck** [comment]
Dharok's set should already be implemented here: https://github.com/LlemonDuck/dps-calculator/blob/master/src/main/java/com/duckblade/osrs/dpscalc/calc/PostCalcTransform.java#L11

However, I see in the equipment check that it is only searching for undamaged components. You can try again with the fully repaired components in the equipment tab, and I'll file this away as a bug for expanding the equipment check to include the damaged armour.

**Comment by LlemonDuck** [comment]
fixed in dd1b1fc0622f012aaa9ebd12238035a1b2736e79, which I included in a request to the plugin-hub, runelite/plugin-hub#2795. It's behind a massive rewrite so it might take a while to be reviewed and I'll close this issue when it's released
