### ISSUE TITLE
Missing smoke battlestaff buffs

### ISSUE THREAD

**Issue by cooperka** [LlemonDuck/dps-calculator#49]
> The [smoke battlestaff](https://oldschool.runescape.wiki/w/Smoke_battlestaff) provides a 10% increase in accuracy and damage when casting spells from the standard spellbook.

This buff is not included in the plugin's calculations. For example, the output of the plugin shows the same DPS for both the smoke battlestaff and the fire battlestaff, when smoke should have a higher attack roll + max hit.

I'll look into the code in sometime in the next few weeks and see what changes this might require.

**Comment by LlemonDuck** [comment]
added in dd1b1fc0622f012aaa9ebd12238035a1b2736e79, which I included in a request to the plugin-hub, runelite/plugin-hub#2795. It's behind a massive rewrite so it might take a while to be reviewed and I'll close this issue when it's released

**Comment by cooperka** [comment]
beautiful commit @LlemonDuck, looks great. cheers.
