### ISSUE TITLE
Void Ranger Set DPS?

### ISSUE THREAD

**Issue by d3nd3** [LlemonDuck/dps-calculator#53]
Can we get this working? I compared d'hide to  void ranger set, no difference in damage.

**Comment by LlemonDuck** [comment]
Are you using the new ornamented void? Can you provide more information (your inputs to each panel)?

I have added support for the ornamented void and generally redone the whole void detection in b0b7375, which is submitted to and pending release on the plugin hub (runelite/plugin-hub#2795). I don't believe this should be an issue after this is released.

**Comment by d3nd3** [comment]
Ok , then I probably have an outdated version from the runelite plugin hub, I assume, it was with basic void knight robes.
