### ISSUE TITLE
New overlay doesn't factor in slayer helm

### ISSUE THREAD

**Issue by fakeyfakertongithub** [LlemonDuck/dps-calculator#62]
Is it possible to have the new overlay that automatically grabs gear/prayer/mob factor in the slayer helm?

**Comment by LlemonDuck** [comment]
This required a change to the core RuneLite client in order to fetch slayer task data, which was completed in runelite/runelite@fcacf4deeb9050d39922d03b599719e69209a5a8.

I added the change to dps-calculator in 8afe03e, and it's pending release to the plugin hub in runelite/plugin-hub#2858
