### ISSUE TITLE
DPS calculation not working with Dharok's Set

### ISSUE THREAD

**Issue by pirssi** [LlemonDuck/dps-calculator#63]
DPS calculation isn't working with full Dharok's equipment set, with the plugin showing "DPS: ???" with the set equipped.

**Comment by LlemonDuck** [comment]
Looks like I broke this in debbac523293801ede40bc90ef585f527e84a99d...

I've fixed it now in 162047b5cbe2ace7cf0f6f02b750c87add3c5b06 and submitted that to the plugin hub in runelite/plugin-hub#2858
