### ISSUE TITLE
Live overlay panel does not honor wilderness checkbox

### ISSUE THREAD

**Issue by IlllIIIIlIIllIl** [LlemonDuck/dps-calculator#65]
Killing wilderness bosses with a wilderness weapon (eg. Craw's bow) shows the correct DPS calculation in the side menu, but the live overlay box does not include the additional wilderness DPS calcs.

Some possible solutions:
- Default this to include wilderness DPS as the majority of users will not be using those weapons outside of the wilderness
- The overlay box can take it's wilderness state from the manually inputted side menu information
- Check in-game location and calculate in/out of wilderness DPS calcs accordingly

**Comment by LlemonDuck** [comment]
It should be reasonably simple to determine if the player is in the wilderness, but I haven't gotten around to it yet.

**Comment by LlemonDuck** [comment]
Added in f74c4047, pending plugin hub review in runelite/plugin-hub#2858
