### ISSUE TITLE
Raids 3 Weapon Effects

### ISSUE THREAD

**Issue by FrancisIris** [LlemonDuck/dps-calculator#81]
It would be great if the new Items could be included within the plugin.
If you have the time it would be much appreciated.

**Comment by FrancisIris** [comment]
Max hit also seems off with the fang selected

**Comment by LlemonDuck** [comment]
item stats added now in https://github.com/LlemonDuck/runelite-wiki-scraper/commit/0bc131b29234645eac69d2654ae0e8947ca2c80c

I have not yet added any of the effects of the new raid items to the calculator

**Comment by StephanBijzitter** [comment]
@LlemonDuck seems Github did not autoclose
