### ISSUE TITLE
Calculation for DPS doesn't work for crystal gear

### ISSUE THREAD

**Issue by fdfddadas** [LlemonDuck/dps-calculator#9]
Dps calculation ignores the 15% damage boost, And likely the accuracy boost too. i'm sure you're aware most items that have special effects their calculations are not included, beyond that this is a really great addition.

**Comment by LlemonDuck** [comment]
Yeah many extra gear effects haven't been added yet, but I'm hoping to get around to them all over time! Thanks for mentioning this one.

**Comment by fdfddadas** [comment]
No problem i appreciate what you’ve done already its great :)

**Comment by LlemonDuck** [comment]
Fixed in 77dedbc60e8c54fbbdd9c0f93bdf6ed8942c670a.

Staged for release 1.3.

**Comment by fdfddadas** [comment]
Awesome, thanks!
